### ISSUE TITLE
Enhance and add features

### ISSUE THREAD

**Issue by Iamkrishnaa** [Iamkrishnaa/school_website#3]
Enhance this project for hacktoberfest

**Comment by Amritanshu02** [comment]
what kind of enhancement do you want?

**Comment by Iamkrishnaa** [comment]
You can add any features like adding new pages for school websites, creating anything.

**Comment by Amritanshu02** [comment]
Okay Sure, So I will work on this issue, please assign it to me.

**Comment by Iamkrishnaa** [comment]
assigned

**Comment by OmDharme** [comment]
can I also work on this, assign this to me too

**Comment by Iamkrishnaa** [comment]
assigned

**Comment by dwidhanis** [comment]
hello! can i work on this ?

**Comment by Iamkrishnaa** [comment]
add some new things in this site and do pull request
